---
- name: Validar sistema operacional suportado
  ansible.builtin.assert:
    that:
      - ansible_facts.os_family == 'RedHat'
      - ansible_facts.distribution in ['CentOS', 'Rocky', 'AlmaLinux']
      - ansible_facts.distribution_major_version | int in [7, 8, 9]
      - >-
        (ansible_facts.distribution_major_version | int != 7)
        or (ansible_facts.distribution == 'CentOS')
    fail_msg: >-
      Sistema nao suportado nesta fase.
      Permitidos: CentOS 7, Rocky Linux 8/9 e AlmaLinux 8/9.

- name: Executar tarefas do CentOS 7
  ansible.builtin.include_tasks: el7.yml
  when: ansible_facts.distribution_major_version | int == 7

- name: Executar tarefas do Rocky ou AlmaLinux 8/9
  ansible.builtin.include_tasks: el8_el9.yml
  when: ansible_facts.distribution_major_version | int in [8, 9]
